# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# env ==================================================================================================================
###
# env::ads_server
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/109/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "ads.ringcentral.com"
  }
}
###
# env::reposerver
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/110/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "repo.ringcentral.com"
  }
}
###
# env::fileserver
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/111/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "UNDEF"
  }
}
###
# env::ldap_servers
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/107/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": ["ams01-c01-adc01.ringcentral.com","ams01-c01-adc02.ringcentral.com"]
  }
}
###
# env::ntpservers
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/108/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": ["ntp1.ringcentral.com","ntp2.ringcentral.com"]
  }
}
###
# ldap_client ==========================================================================================================
# ldap_client::binddn
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/477/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "CN=Ldap User,CN=Users,dc=ringcentral,dc=com"
  }
}
###
# ldap_client::bindpw
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/384/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
"override_value": {
"match": "location=aws76",
"value": "Fh5_dv3_g"
}
}
###
# ldap_client::ldap_dc
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/383/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "DC=ringcentral,DC=com"
  }
}
###
# ldap_client::ldap_domain
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/385/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "ringcentral.com"
  }
}

###
# postfix_rc ======================================+====================================================================
# postfix_rc::smarthost
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/380/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "smtp-relay.ringcentral.com"
  }
}
###
# postfix_rc::masqdomain
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/381/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "ringcentral.com"
  }
}
###
# sendmail_rc ==========================================================================================================
# sendmail_rc::masqdomain
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/12/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "ringcentral.com"
  }
}
###
# sendmail_rc::smarthost
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/13/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "smtp-relay.ringcentral.com"
  }
}
###
# sendmail_rc::masqroot
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/14/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "root-notify@c01.ringcentral.com"
  }
}
###
# sendmail_rc::rootemail
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/15/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "root-notify@c01.ringcentral.com"
  }
}
###
# dnsclient_rc::suffix ==========================================================================================================
# dnsclient_rc::suffix::suffixtoadd
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/25/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "ringcentral.com"
  }
}
###
# logbackup_rc ==========================================================================================================
# logbackup_rc::logserver_share
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/6/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "aws76-logbackup.c01.ringcentral.com/rclogbackup-aws76"
  }
}
###
# logbackup_rc::influxdb_host
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/578/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "http://ams01-influxdb.int.ringcentral.com:8086"
  }
}
###
# wazuh ==========================================================================================================
# wazuh::server
POST https://ams01-puppet.ringcentral.com/api/v2/smart_class_parameters/552/override_values
Authorization: Basic alexander.simonov 9643707470Sam!
Content-Type: application/json

{
  "override_value": {
    "match": "location=aws76",
    "value": "10.48.36.97"
  }
}
###