[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/gorilla/context"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.6.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[[constraint]]
  name = "gopkg.in/ldap.v3"
  version = "3.0.3"

[prune]
  go-tests = true
  unused-packages = true
